import 'package:drift/drift.dart';

import '../models/rawi_item.dart';
// Conditional import for platform-specific connection
// FFI (native / Flutter mobile / desktop) -> connection_native.dart
// Web (dart.library.js_interop) -> connection_web.dart
import 'connection/connection_native.dart'
    if (dart.library.js_interop) 'connection/connection_web.dart'
    as impl;

// Part file will be generated by build_runner
part 'rawi_database.g.dart';

typedef RawiConnectionFactory = DatabaseConnection Function();

// Use RawiItem directly as the row class (no auto-generated RawiData)
@UseRowClass(RawiItem, constructor: 'fromDatabase')
class Rawi extends Table {
  /// Match existing database schema: key (int) and value (text)
  IntColumn get key => integer()(); // Non-null unique integer (ID)
  @override
  Set<Column> get primaryKey => {key};

  TextColumn get value =>
      text()(); // Arabic name (already normalized, no diacritics)

  // Note: No additional indexes needed - database already has unique constraint on key
  // value column already contains normalized Arabic text (no diacritics)
}

@DriftDatabase(tables: [Rawi])
class RawiDatabase extends _$RawiDatabase {
  static RawiConnectionFactory _connectionFactory = impl.openConnection;

  // Constructor uses platform-specific connection
  RawiDatabase() : super(_connectionFactory());

  @override
  int get schemaVersion => 1;

  /// Count total narrators or filtered by query.
  ///
  /// If [query] is provided, counts narrators matching the search.
  /// Otherwise, returns total count.
  Future<int> countRawi({String? query}) async {
    final countExpr = rawi.key.count();
    final countQuery = selectOnly(rawi)..addColumns([countExpr]);

    if (query != null) {
      countQuery.where(rawi.value.like('%$query%'));
    }

    final result = await countQuery.getSingle();
    return result.read(countExpr) ?? 0;
  }

  /// Close the database connection.
  ///
  /// Call this when done using the database to free resources.
  Future<void> dispose() => close();

  // Note: This is a read-only database bundled with the app
  // No migrations needed - schema is fixed

  /// Get all narrators with pagination.
  ///
  /// ⚠️ Warning: Use pagination! There are ~14,451 narrators.
  /// Don't call this with large limits.
  ///
  /// Parameters:
  /// - [limit]: Maximum number of results (default: 100)
  /// - [offset]: Number of results to skip (default: 0)
  Future<List<RawiItem>> getAllRawi({int limit = 100, int offset = 0}) {
    return (select(rawi)..limit(limit, offset: offset)).get();
  }

  /// Get a specific narrator by ID.
  ///
  /// Returns null if not found.
  /// Complexity: O(log n) with indexed primary key.
  Future<RawiItem?> getRawiById(int id) {
    return (select(rawi)..where((t) => t.key.equals(id))).getSingleOrNull();
  }

  /// Get multiple narrators by their IDs.
  ///
  /// Useful for fetching popular narrators from constants.
  Future<List<RawiItem>> getRawiByKeys(List<int> keys) {
    return (select(rawi)..where((t) => t.key.isIn(keys))).get();
  }

  /// Search narrators by name (already normalized in database).
  ///
  /// The database value column contains pre-normalized Arabic text
  /// (no diacritics), so no normalization is needed for search.
  ///
  /// Parameters:
  /// - [query]: Search text (will be wrapped with % for LIKE query)
  /// - [limit]: Maximum number of results (default: 20)
  /// - [offset]: Number of results to skip for pagination (default: 0)
  ///
  /// Returns list of matching narrators, ordered by key.
  Future<List<RawiItem>> searchRawi(
    String query, {
    int limit = 20,
    int offset = 0,
  }) {
    return (select(rawi)
          ..where((t) => t.value.like('%$query%'))
          ..limit(limit, offset: offset))
        .get();
  }

  /// Override the connection factory used when instantiating new databases.
  static void configureConnection(RawiConnectionFactory factory) {
    _connectionFactory = factory;
  }

  /// Reset the connection factory back to the platform default.
  static void resetConnection() {
    _connectionFactory = impl.openConnection;
  }
}
